name: Kiali CI

on:
  # Run on master and release branches
  push:
    branches: [master, "^v\\d+\\.\\d+$"]
  pull_request:
    branches: [master, "^v\\d+\\.\\d+$"]

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-latest
    outputs:
      # This workflow can run on either a PR or release. GITHUB_BASE_REF is only
      # set when this workflow is run against a PR. When run against a PR, we want
      # to use the branch we are running against: GITHUB_BASE_REF. When run
      # as a release, we want to use the current branch ref: GITHUB_REF_NAME.
      target-branch: ${{ github.base_ref || github.ref_name }}
    steps:
      # The initialize job gathers variables for later use in jobs.
      # We are using this technique rather environment variables because at the moment, they won't work with reusable jobs.
      # A positive side effect of this is that we can print all variables at start for debugging and troubleshooting.
      - run: echo "target-branch -> ${{ github.base_ref || github.ref_name }}"
      - run: echo "ref_name -> ${{ github.ref_name }}"
  build_backend:
    name: Build backend
    uses: ./.github/workflows/build-backend.yml
    needs: [initialize]
  build_frontend:
    name: Build frontend
    uses: ./.github/workflows/build-frontend.yml
    needs: [initialize]
    with:
      target_branch: ${{needs.initialize.outputs.target-branch}}
  integration_tests_backend:
    name: Run backend integration tests
    uses: ./.github/workflows/integration-tests-backend.yml
    needs: [initialize, build_backend, build_frontend]
    with:
      target_branch: ${{needs.initialize.outputs.target-branch}}
  integration_tests_frontend:
    name: Run frontend integration tests
    uses: ./.github/workflows/integration-tests-frontend.yml
    needs: [initialize, build_backend, build_frontend]
    with:
      target_branch: ${{needs.initialize.outputs.target-branch}}
